# Day 10 - Adapter Array
## Investigation Notebook

In [103]:
import numpy as np
import collections

In [7]:
def load_data(t):
    if t == 'test':
        fp = '../data/day-10-test.txt'
    elif t == 'full':
        fp = '../data/day-10.txt'
    else:
        raise Exception('Invalid File Input.')
    with open(fp, 'r') as f:
        lines = f.readlines()
        return np.array([int(line.strip()) for line in lines])

In [9]:
data = load_data('test').sort()

In [17]:
diffs = np.ediff1d(data)
c = collections.Counter(diffs)
print(c)

Counter({1: 21, 3: 9})


In [68]:
def get_jolt_differences(dat):
    # Add 0 and max + 3 for start and final value
    dat = np.append(dat, [0, max(dat) + 3])
    dat.sort()
    print(dat)
    diffs = np.ediff1d(dat)
    print(diffs)
    c = coll.Counter(diffs)
    return {1:c[1], 3:c[3]}

In [69]:
test_data = load_data('test')
a = get_jolt_differences(test_data)
print(a)

[ 0  1  2  3  4  7  8  9 10 11 14 17 18 19 20 23 24 25 28 31 32 33 34 35
 38 39 42 45 46 47 48 49 52]
[1 1 1 1 3 1 1 1 1 3 3 1 1 1 3 1 1 3 3 1 1 1 1 3 1 3 3 1 1 1 1 3]
{1: 22, 3: 10}


In [70]:
def part_one():
    data = load_data('full')
    r = get_jolt_differences(data)
    print(r)
    print('Part One:', r[1] * r[3])

In [71]:
part_one()

[  0   1   2   3   6   7   8   9  10  13  14  15  16  19  22  23  24  25
  28  29  32  33  36  39  42  43  44  45  48  49  50  53  56  57  58  59
  62  65  68  69  70  71  72  75  78  81  82  83  84  87  90  93  94  95
  98 101 102 103 104 107 108 109 112 113 114 115 116 119 120 121 122 123
 126 129 130 131 132 135 138 139 140 141 144 145 148 149 150 151 152 155
 156 157 160 163 166 167 168 169 170 173 174 175 176 179]
[1 1 1 3 1 1 1 1 3 1 1 1 3 3 1 1 1 3 1 3 1 3 3 3 1 1 1 3 1 1 3 3 1 1 1 3 3
 3 1 1 1 1 3 3 3 1 1 1 3 3 3 1 1 3 3 1 1 1 3 1 1 3 1 1 1 1 3 1 1 1 1 3 3 1
 1 1 3 3 1 1 1 3 1 3 1 1 1 1 3 1 1 3 3 3 1 1 1 1 3 1 1 1 3]
{1: 65, 3: 38}
Part One: 2470


## Part Two

So for each item, we need to look how many options there are one, two or three steps after it.

In [81]:
data

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11, 14, 17, 18, 19, 20, 23, 24, 25,
       28, 31, 32, 33, 34, 35, 38, 39, 42, 45, 46, 47, 48, 49])

In [79]:
def num_possible_jumps(data, value):
    data = data[(data > value) & (data <= value + 3)]
    return data

In [82]:
possible_jumps(data, 11)

array([14])

This option isn't going to work, so I'm going to copy an example from here. I think it's really good and uses `defaultdict` which I don't think I've used before.

In [83]:
possibilities = coll.defaultdict(int)

In [104]:
# There's 1 way of starting
possibilities[0] = 1
print(data)

for val in data:
    possibilities[val] = possibilities[val - 1] + possibilities[val - 2] + possibilities[val - 3] 

print(possibilities[max(data)])

[ 1  2  3  4  7  8  9 10 11 14 17 18 19 20 23 24 25 28 31 32 33 34 35 38
 39 42 45 46 47 48 49]
1740200


In [110]:
def part_two():
    data = load_data('full')
    data.sort()
    possibilities = collections.defaultdict(int)
    # intialise with 1 to represent the final possible step
    possibilities[0] = 1

    for val in data:
        possibilities[val] = possibilities[val - 1] + possibilities[val - 2] + possibilities[val - 3] 
    
    return possibilities[max(data)]

part_two()

1973822685184